import React, { useMemo } from 'react';
import type {
  BeatReviewClusterHintCandidateRecord,
  BeatReviewItemRecord,
} from '../../src/board/types';
import type { Idea } from '../../src/types';
import { NudgeCard } from './primitives/NudgeCard';

/**
 * SynthesizerProposalNudges — bo-143 (M3 / Screen 02).
 *
 * Surfaces cluster proposals produced by the Synthesizer roles
 * (`boardClusterer`, `groupThemer`, `approachSynthesizer`) through the
 * canonical `<NudgeCard>` accept/preview/dismiss triple.
 *
 * Cluster proposals already exist as `BeatReviewItemRecord`s of kind
 * `cluster_hint`, generated by the cluster beat (`runManualBoardBeat`) and
 * staged into a `BeatReviewSession`. Today they're applied via the
 * `BeatReviewPanel` modal and the inline Companion-rail review section.
 * This component layers a lighter, always-visible NudgeCard list so the user
 * can act on each proposal in isolation:
 *
 *  - **Accept** runs the existing apply mutation (`onAccept`) which calls into
 *    `useBeatReviewActions.handleKeep` → groups the ideas and sets the
 *    Synthesizer-named theme/sharedQuestion on the resulting `IdeaGroup`.
 *  - **Preview** lifts the cluster's idea ids to the parent so the canvas can
 *    paint a transient halo around them via `ClusterHaloLayer`'s active style.
 *  - **Dismiss** runs the existing scratch mutation (`onDismiss`) which marks
 *    the proposal scratched and removes it from the queue.
 *
 * The component is purely presentational — preview state and the apply/scratch
 * controllers live in `BoardScreen`.
 */

export interface SynthesizerProposalNudgesProps {
  /**
   * Active beat review items (any status). The component filters to pending
   * `cluster_hint` proposals so already-applied / dismissed entries fall off
   * the rail without further work in the host.
   */
  items: BeatReviewItemRecord[];
  /** Live ideas, used to resolve titles for the preview body. */
  ideas: Idea[];
  /** Item id currently flagged as previewed (highlights the matching halo). */
  previewItemId?: string | null;
  /** Map of item id → busy state from `useBeatReviewActions.busyByItem`. */
  busyByItem?: Record<string, 'keep' | 'scratch' | null>;
  /** Apply the cluster proposal (group ideas + set theme). */
  onAccept: (itemId: string) => void;
  /** Toggle the canvas preview halo for the given proposal. */
  onPreviewToggle: (item: ClusterHintReviewItem | null) => void;
  /** Dismiss / scratch the proposal. */
  onDismiss: (itemId: string) => void;
  /** Optional override for the rail's section heading. */
  title?: string;
}

export type ClusterHintReviewItem = BeatReviewItemRecord & {
  candidate: BeatReviewClusterHintCandidateRecord;
};

function isClusterHintItem(item: BeatReviewItemRecord): item is ClusterHintReviewItem {
  return item.candidate.kind === 'cluster_hint';
}

function compactText(value: string, maxLength: number): string {
  const trimmed = value.trim();
  if (trimmed.length <= maxLength) return trimmed;
  return `${trimmed.slice(0, maxLength - 1).trim()}…`;
}

function summariseMembers(item: ClusterHintReviewItem, ideas: Idea[]): string {
  const ideaIds = item.candidate.payload.ideaIds ?? item.candidate.affectedIdeaIds ?? [];
  if (ideaIds.length === 0) return 'No ideas referenced yet.';
  const ideaById = new Map(ideas.map(idea => [idea.id, idea] as const));
  const titles = ideaIds
    .map(id => ideaById.get(id)?.rawText.split('\n')[0]?.trim())
    .filter((title): title is string => Boolean(title))
    .map(title => compactText(title, 36));
  if (titles.length === 0) {
    return `${ideaIds.length} idea${ideaIds.length === 1 ? '' : 's'} on the board.`;
  }
  if (titles.length <= 2) return titles.join(' · ');
  const overflow = ideaIds.length - 2;
  return `${titles.slice(0, 2).join(' · ')} +${overflow} more`;
}

export function SynthesizerProposalNudges({
  items,
  ideas,
  previewItemId = null,
  busyByItem,
  onAccept,
  onPreviewToggle,
  onDismiss,
  title = 'Synthesizer proposals',
}: SynthesizerProposalNudgesProps): React.ReactElement | null {
  const pendingClusterHints = useMemo(() => {
    return items
      .filter(isClusterHintItem)
      .filter(item => item.status === 'pending')
      .sort((left, right) => left.createdAt - right.createdAt);
  }, [items]);

  if (pendingClusterHints.length === 0) return null;

  return (
    <section
      className="bo-card-surface flex flex-col gap-2"
      aria-label={title}
      style={{
        borderRadius: 14,
        border: '2px solid var(--ink)',
        background: 'var(--paper)',
        boxShadow: '3px 3px 0 var(--ink)',
        padding: 12,
        fontFamily: 'var(--f-hand-body)',
        color: 'var(--ink)',
      }}
    >
      <header
        className="flex items-center justify-between gap-2"
        style={{
          paddingBottom: 8,
          borderBottom: '1.4px dashed var(--hairline)',
        }}
      >
        <p
          style={{
            margin: 0,
            fontFamily: 'var(--f-mono)',
            fontSize: 10,
            letterSpacing: '0.18em',
            textTransform: 'uppercase',
            color: 'var(--ink-faint)',
            fontWeight: 700,
          }}
        >
          {title}
        </p>
        <span
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            padding: '2px 10px',
            borderRadius: 999,
            border: '1.5px solid var(--accent-cluster)',
            background: 'var(--sticky-green)',
            fontFamily: 'var(--f-mono)',
            fontSize: 10,
            letterSpacing: '0.12em',
            textTransform: 'uppercase',
            fontWeight: 700,
            color: 'var(--ink)',
          }}
        >
          {pendingClusterHints.length} pending
        </span>
      </header>

      <div className="flex flex-col gap-2">
        {pendingClusterHints.map(item => {
          const candidate = item.candidate.payload;
          const previewing = previewItemId === item.id;
          const busy = busyByItem?.[item.id] ?? null;
          const eyebrow = `Cluster role · ${item.beat}`;
          return (
            <NudgeCard
              key={item.id}
              eyebrow={eyebrow}
              title={candidate.theme || item.candidate.label || 'Cluster proposal'}
              body={compactText(candidate.sharedQuestion || item.candidate.summary || '', 140)}
              acceptLabel={busy === 'keep' ? 'Accepting…' : 'Accept'}
              onAccept={busy ? undefined : () => onAccept(item.id)}
              previewLabel={previewing ? 'Hide preview' : 'Preview'}
              onPreview={() => onPreviewToggle(previewing ? null : item)}
              dismissLabel={busy === 'scratch' ? 'Dismissing…' : 'Dismiss'}
              onDismiss={busy ? undefined : () => onDismiss(item.id)}
              ariaLabel={`Cluster proposal: ${candidate.theme || 'untitled'}`}
            >
              {summariseMembers(item, ideas)}
            </NudgeCard>
          );
        })}
      </div>
    </section>
  );
}

export default SynthesizerProposalNudges;
