import type { ActiveTabToolContext } from './webmcp/types';
export type { ActiveTabToolContext } from './webmcp/types';
import type { BeatSourceRef } from './beats/types';

export type IdeaStatus = 'captured' | 'in_progress' | 'blocked' | 'ready_for_handoff' | 'archived' | 'discarded';
// Phase may be an integer (main phase 0-8) or a decimal (micro step, e.g. 0.5, 2.5, 4.5).
// The canonical sub-phase registry lives in src/orchestrator/subPhases.ts.
export type Phase = number;
export type BoardId = string;
export type Density = 'simple' | 'standard' | 'expert';
export type ProviderId = 'gemini' | 'openai' | 'anthropic';

// --- Provider-agnostic message format (like OpenAI chat schema) ---
export interface LlmMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

// --- Role-specific artifacts produced by each micro-agent ---
export type Severity = 'high' | 'medium' | 'low';
export type ResolutionMode = 'ask' | 'assume' | 'prototype' | 'research' | 'defer';
export type AmbiguityResolutionStatus = 'open' | 'resolved' | 'deferred' | 'dismissed';
export type IdeaActorType = 'user' | 'ai' | 'tool' | 'system';
export type IdeaActorSource = 'canvas' | 'webmcp' | 'workspace' | 'beat' | 'system';
export type AmbiguityType =
  | 'terminology' | 'goal' | 'scope' | 'audience' | 'ux'
  | 'data_process' | 'integration' | 'operational'
  | 'policy_legal_security' | 'ownership';

export interface Ambiguity {
  id: string;
  type: AmbiguityType;
  plainLanguage: string;
  severity: Severity;
  resolutionMode: ResolutionMode;
  resolution?: {
    status: AmbiguityResolutionStatus;
    note?: string;
    resolvedBy?: string;
    resolvedAt?: number;
  };
}

export interface ClarificationQuestion {
  id: string;
  ambiguityId: string;
  question: string;
  answer?: string;
}

export interface Approach {
  id: string;
  label: string;
  summary: string;
  scores: {
    speed: number; cost: number; complexity: number; maintainability: number;
    teamBurden: number; userValue: number; operationalLoad: number;
    adoptionRisk: number; reversibility: number; complianceRisk: number;
  };
  rejectionReason?: string;
}

export interface RiskItem {
  id: string;
  description: string;
  likelihood: Severity;
  impact: Severity;
  sourceQuestionId?: string;
  sourceQuestion?: string;
  userNote?: string;
  createdAt?: number;
  updatedAt?: number;
}

// Proactive "outside-the-box" content generated by micro-step roles between main phases.
export type LensKind = 'outside_in' | 'analogy' | 'contrarian' | 'user_voice';
export type UserVerdict = 'pinned' | 'dismissed' | 'pending';

export interface LensEntry {
  id: string;
  kind: LensKind;
  frame: string;           // e.g. "If this were a cooking show…" / "A hostile regulator reads this spec…"
  insight: string;         // the actual angle / reframing
  provocation: string;     // the question that forces the user to think
  verdict: UserVerdict;
  userNote?: string;       // user's reaction/reply
}

export type ChallengeStance = 'accept' | 'defer' | 'rebut' | 'pending';

export interface ChallengeEntry {
  id: string;
  critique: string;        // devil's-advocate punch
  evidenceAsk: string;     // what proof would put this to rest
  stance: ChallengeStance;
  userRebuttal?: string;
}

export interface StressResult {
  id: string;
  ruleIndex: number;       // index into briefState.mustStayTrueRules
  edgeCase: string;        // the scenario that might break the rule
  breakMode: string;       // why it breaks
  handled: boolean;        // user marked as addressed
  userResponse?: string;
}

export interface BeadSuggestion {
  phase: Phase;
  reason: string;
  suggestedAt: number;
  actorType: IdeaActorType;
  actorSource: IdeaActorSource;
  actorLabel?: string;
}

export interface BeadReviewFlag {
  id: string;
  phase: Phase;
  reason: string;
  flaggedAt: number;
  actorType: IdeaActorType;
  actorSource: IdeaActorSource;
  actorLabel?: string;
}

export interface BeadCoordinationState {
  suggestedNext?: BeadSuggestion;
  reviewFlags: BeadReviewFlag[];
}

export interface BriefState {
  problemStatement?: string;
  audience?: string;
  desiredOutcome?: string;
  mustStayTrueRules: string[];
  chosenApproachId?: string;
  approaches: Approach[];
  rejectedApproaches: Approach[];
  risks: RiskItem[];
  successCriteria: string[];
  outOfScope: string[];
  openQuestions: string[];
  nextStep?: 'planning' | 'prototyping' | 'research' | 'stakeholder_review' | 'defer';
  // New micro-step buckets — populated by proactive LLM roles between main phases.
  lenses: LensEntry[];
  challenges: ChallengeEntry[];
  stressResults: StressResult[];
}

// Floating-canvas panel geometry. Optional on older ideas; defaults filled at hydrate time.
export interface Panel {
  x: number;
  y: number;
  width: number;
  height: number;
  groupId?: string; // if set, the idea belongs to a group (see IdeaGroup)
}

// A group of related ideas formed by proximity on the canvas.
export interface IdeaGroup {
  id: string;
  boardId?: BoardId;
  theme?: string;           // short LLM-generated theme ("Things that touch auth")
  sharedQuestion?: string;  // a question that holds the group together
  ideaIds: string[];
  createdAt: number;
  updatedAt: number;
}

// --- Scout suggestions — "ghost" ideas proposed by the outsideKnowledgeScout ---
// Surfaced onto the canvas in a distinct colour. The user can admit (promote to
// a real idea), elaborate (ask the scout for more detail / rationale), or
// dismiss (drop it from the pool). Admitted suggestions reference the new idea.
export type ScoutSuggestionStatus = 'pending' | 'admitted' | 'dismissed';

export interface ScoutSuggestion {
  id: string;
  boardId?: BoardId;
  rawText: string;                      // the suggestion body, in idea-panel shape
  rationale: string;                    // why the scout thinks this is worth considering
  source: string;                       // e.g. "analogy: healthcare triage", "contrarian take", "adjacent field: ops"
  automationKey?: string;               // deterministic key for AI-triggered dedupe across peers
  status: ScoutSuggestionStatus;
  sourceIdeaIds?: string[];             // exact source pair for cross-pollinated suggestions when applicable
  relatedIdeaIds?: string[];            // ids of board ideas the scout leaned on
  elaboration?: string;                 // fleshed-out version if the user asked for elaboration
  admittedIdeaId?: string;              // if admitted, the id of the promoted real Idea
  panel?: Panel;                        // floating-canvas position for the ghost panel
  createdAt: number;
  updatedAt: number;
}

// --- Cross-board connections surfaced by the connectionFinder LLM role ---
// A connection links two or more ideas (possibly including discarded ones).
// supportingDocIds refer to SupportingDoc ids when the evidence came from docs.
export type ConnectionKind = 'builds_on' | 'contradicts' | 'revives_killed' | 'shared_theme';
export type ConnectionStrength = 'weak' | 'medium' | 'strong';

export interface Connection {
  id: string;
  boardId?: BoardId;
  kind: ConnectionKind;
  ideaIds: string[];            // usually 2, may be more for shared_theme
  supportingDocIds?: string[];  // ids of docs the LLM cited as evidence
  rationale: string;            // 1-3 sentences explaining the link
  strength: ConnectionStrength;
  createdAt: number;
}

export type CritiqueStatus = 'active' | 'dismissed';

export interface IdeaCritique {
  id: string;
  boardId?: BoardId;
  ideaId: string;
  critique: string;
  evidenceAsk: string;
  automationKey?: string;               // deterministic key for AI-triggered dedupe across peers
  status: CritiqueStatus;
  source: 'devils_advocate';
  createdAt: number;
  updatedAt: number;
}

// Supporting document attached to an idea — NOT an idea itself, but context
// that the LLM can reference while moving the idea through the phases.
// Refined once at upload into a short summary + a list of facts the orchestrator
// can inject into phase prompts.
export type SupportingDocStatus = 'processing' | 'ready' | 'failed';

export interface SupportingDoc {
  id: string;
  boardId?: BoardId;
  ideaId: string;
  title: string;          // user-provided or auto-generated from the first line
  rawText: string;        // the pasted content (trimmed, capped client-side)
  summary?: string;       // 1-2 sentences, LLM-produced
  facts: string[];        // 3-10 extracted facts, LLM-produced
  status: SupportingDocStatus;
  error?: string;         // only populated when status === 'failed'
  createdAt: number;
  updatedAt: number;
}

export interface Idea {
  id: string;
  boardId?: BoardId;
  rawText: string;
  tags: string[];
  createdAt: number;
  updatedAt: number;
  lastTurnAt?: number;
  status: IdeaStatus;
  phase: Phase;
  briefState: BriefState;
  ambiguities: Ambiguity[];
  clarifications: ClarificationQuestion[];
  turnLog: LlmMessage[];              // flattened audit trail across all micro-agent calls
  liveToolContext?: ActiveTabToolContext; // WebMCP tools detected on the active tab at Phase 0/1
  artifactMd?: string;                // rendered workspace markdown (derived from briefState)
  readiness: 'red' | 'yellow' | 'green';
  providerUsed?: ProviderId;
  panel?: Panel;                       // floating-canvas position + group membership
  mergedFrom?: string[];               // if this idea was merged, the ids of the originals
  insights?: IdeaInsight[];
  beadCoordination?: BeadCoordinationState;
}

export interface IdeaInsight {
  id: string;
  text: string;
  sourceRefs: BeatSourceRef[];
  relatedGroupIds?: string[];
  beatRunId?: string;
  createdAt: number;
}

export interface ProviderCredentials {
  gemini?: string;
  openai?: string;
  anthropic?: string;
}

export type BoardThemeMode = 'whiteboard' | 'sketch';

export interface Settings {
  credentials: ProviderCredentials;
  activeProvider: ProviderId;
  activeModel: string;                // e.g. 'gemini-2.5-pro', 'gpt-4o', 'claude-sonnet-4-6'
  density: Density;
  boardTheme: BoardThemeMode;
}

// --- ct-mcp payload that every micro-agent call is built from ---
export interface CtMcpPayload {
  roleSystemPrompt: string;           // the micro-agent's role definition
  briefState: BriefState;             // current state (feeds constraint-forcing)
  detectedAmbiguities: Ambiguity[];   // what's still unresolved
  mustStayTrueRules: string[];        // cross-reference target (constraint forcing)
  task: string;                       // the specific ask for this turn
  outputJsonSchema: object;           // zod-derived JSON schema the model must return
  liveToolContext?: ActiveTabToolContext; // WebMCP tools from active tab (Phase 0/1 only)
  supportingDocs?: SupportingDoc[];   // refined reference material attached to this idea
}
